project_id = "ydljsdscdnqrqnjvqela"

[functions.reset-client-password]
verify_jwt = false

[functions.create-client-auth]
verify_jwt = false

[functions.invite-client]
verify_jwt = false

[functions.migrate-documents-to-storage]
verify_jwt = false

[functions.send-smtp-email]
verify_jwt = false

[functions.generate-share-link]
verify_jwt = false

[functions.get-shared-files]
verify_jwt = false

[functions.send-visit-reminders]
verify_jwt = false

[functions.sync-all-imap-emails]
verify_jwt = false
