project_id = "ydljsdscdnqrqnjvqela"

[functions.resend-agent-invitation]
verify_jwt = true

[functions.reset-client-password]
verify_jwt = false

[functions.invite-client]
verify_jwt = false

[functions.migrate-documents-to-storage]
verify_jwt = false

[functions.send-smtp-email]
verify_jwt = true

[functions.generate-share-link]
verify_jwt = false

[functions.get-shared-files]
verify_jwt = false

[functions.send-visit-reminders]
verify_jwt = false

[functions.sync-all-imap-emails]
verify_jwt = false

[functions.send-recommendation-email]
verify_jwt = false

[functions.send-etat-lieux-reminders]
verify_jwt = false

[functions.send-signature-reminders]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-abaninja-client]
verify_jwt = false

[functions.create-abaninja-invoice]
verify_jwt = false

[functions.send-mandat-pdf]
verify_jwt = false

[functions.abaninja-webhook]
verify_jwt = false

[functions.resend-abaninja-invoice]
verify_jwt = false

[functions.send-invoice-reminders]
verify_jwt = false

[functions.send-pending-notification-emails]
verify_jwt = false

[functions.notify-unassigned-clients]
verify_jwt = false

[functions.notify-unassigned-clients.schedule]
cron = "0 */12 * * *"

[functions.get-mapbox-token]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-mandat-contract]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.create-proprietaire]
verify_jwt = false

[functions.generate-full-mandat-pdf]
verify_jwt = false
