project_id = "ydljsdscdnqrqnjvqela"

[functions.reset-client-password]
verify_jwt = false

[functions.create-client-auth]
verify_jwt = false

[functions.invite-client]
verify_jwt = false

[functions.migrate-documents-to-storage]
verify_jwt = false