// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-pending-postulations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/guard.ts
import { ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/guard.ts
async function requireAutomationOperator(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new ToolError("401 unauthorized: jeton OAuth manquant ou invalide.");
  }
  const userId = ctx.getUserId();
  if (!userId) {
    throw new ToolError("401 unauthorized: jeton sans sujet (sub).");
  }
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("user_roles").select("role").eq("user_id", userId);
  if (error) {
    throw new ToolError(`403 forbidden: impossible de v\xE9rifier le r\xF4le (${error.message}).`);
  }
  const roles = (data ?? []).map((r) => r.role);
  if (!roles.includes("automation_operator")) {
    throw new ToolError(
      "403 forbidden: le r\xF4le applicatif \xAB automation_operator \xBB est requis pour cet outil."
    );
  }
  return { supabase, userId, roles };
}
function toZurichISO(value) {
  if (!value) return null;
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  const parts = new Intl.DateTimeFormat("sv-SE", {
    timeZone: "Europe/Zurich",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false
  }).format(date);
  const local = parts.replace(" ", "T");
  const asUtc = (/* @__PURE__ */ new Date(`${local}Z`)).getTime();
  const offsetMinutes = Math.round((asUtc - date.getTime()) / 6e4);
  const sign = offsetMinutes >= 0 ? "+" : "-";
  const abs = Math.abs(offsetMinutes);
  const hh = String(Math.floor(abs / 60)).padStart(2, "0");
  const mm = String(abs % 60).padStart(2, "0");
  return `${local}${sign}${hh}:${mm}`;
}
function textResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
async function auditLog(supabase, entry) {
  const { error } = await supabase.from("automation_mcp_audit").insert(entry);
  if (error) console.warn("[mcp-audit]", error.message);
}

// src/lib/mcp/tools/list-pending-postulations.ts
var list_pending_postulations_default = defineTool({
  name: "list_pending_postulations",
  title: "Postulations \xE0 faire",
  description: "Liste les postulations en attente de d\xE9p\xF4t (offres au statut \xAB souhaite_postuler \xBB), avec le client concern\xE9.",
  inputSchema: {
    limit: z.number().int().describe("Nombre maximum de postulations \xE0 retourner (d\xE9faut 25, max 100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const { supabase } = await requireAutomationOperator(ctx);
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const { data: offres, error } = await supabase.from("offres").select("id, created_at, adresse, prix, pieces, surface, etage, type_bien, lien_annonce, statut, client_id").eq("statut", "souhaite_postuler").order("created_at", { ascending: false }).limit(max);
    if (error) throw new Error(error.message);
    const rows = offres ?? [];
    const clientIds = [...new Set(rows.map((o) => o.client_id).filter(Boolean))];
    const clientById = /* @__PURE__ */ new Map();
    if (clientIds.length) {
      const { data: clients } = await supabase.from("clients").select("id, user_id").in("id", clientIds);
      for (const c of clients ?? []) clientById.set(c.id, { user_id: c.user_id });
    }
    const userIds = [...new Set([...clientById.values()].map((c) => c.user_id).filter(Boolean))];
    const profileById = /* @__PURE__ */ new Map();
    if (userIds.length) {
      const { data: profiles } = await supabase.from("profiles").select("id, prenom, nom, email").in("id", userIds);
      for (const p of profiles ?? []) profileById.set(p.id, { prenom: p.prenom, nom: p.nom, email: p.email });
    }
    return textResult({
      count: rows.length,
      postulations: rows.map((o) => {
        const userId = clientById.get(o.client_id)?.user_id ?? null;
        const profile = userId ? profileById.get(userId) : void 0;
        return {
          postulation_id: o.id,
          created_at: toZurichISO(o.created_at),
          adresse: o.adresse,
          prix: o.prix,
          pieces: o.pieces,
          surface: o.surface,
          etage: o.etage,
          type_bien: o.type_bien,
          lien_annonce: o.lien_annonce,
          statut: o.statut,
          client: {
            client_id: o.client_id,
            prenom: profile?.prenom ?? null,
            nom: profile?.nom ?? null,
            email: profile?.email ?? null
          }
        };
      })
    });
  }
});

// src/lib/mcp/tools/get-postulation-context.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_postulation_context_default = defineTool2({
  name: "get_postulation_context",
  title: "Contexte d'une postulation",
  description: "Retourne le dossier born\xE9 d'UNE postulation : l'offre, le client, ses co-candidats et les documents li\xE9s. Aucun autre dossier n'est accessible.",
  inputSchema: {
    postulation_id: z2.string().uuid().describe("Identifiant de l'offre (postulation).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ postulation_id }, ctx) => {
    const { supabase } = await requireAutomationOperator(ctx);
    const { data: offre, error } = await supabase.from("offres").select(
      "id, created_at, date_envoi, adresse, prix, pieces, surface, etage, type_bien, description, lien_annonce, statut, disponibilite, contact_gerance, contact_annonceur, contact_visite, client_id"
    ).eq("id", postulation_id).maybeSingle();
    if (error) throw new Error(error.message);
    if (!offre) throw new ToolError2("404 not found: postulation introuvable ou non autoris\xE9e.");
    const { data: client } = await supabase.from("clients").select(
      "id, user_id, nationalite, type_permis, situation_familiale, profession, employeur, revenus_mensuels, charges_mensuelles, type_contrat, date_naissance, adresse, nombre_occupants, animaux, statut"
    ).eq("id", offre.client_id).maybeSingle();
    let profile = null;
    if (client?.user_id) {
      const { data } = await supabase.from("profiles").select("id, prenom, nom, email, telephone").eq("id", client.user_id).maybeSingle();
      if (data) profile = { prenom: data.prenom, nom: data.nom, email: data.email, telephone: data.telephone };
    }
    const { data: candidates } = await supabase.from("client_candidates").select(
      "id, type, prenom, nom, email, telephone, date_naissance, nationalite, type_permis, situation_familiale, profession, employeur, type_contrat, revenus_mensuels, charges_mensuelles"
    ).eq("client_id", offre.client_id);
    const { data: documents } = await supabase.from("documents").select("id, nom, type_document, type, taille, statut, date_upload, candidate_id").or(`client_id.eq.${offre.client_id}${client?.user_id ? `,user_id.eq.${client.user_id}` : ""}`).order("date_upload", { ascending: false }).limit(300);
    return textResult({
      postulation: {
        postulation_id: offre.id,
        created_at: toZurichISO(offre.created_at),
        date_envoi: toZurichISO(offre.date_envoi),
        adresse: offre.adresse,
        prix: offre.prix,
        pieces: offre.pieces,
        surface: offre.surface,
        etage: offre.etage,
        type_bien: offre.type_bien,
        description: offre.description,
        lien_annonce: offre.lien_annonce,
        statut: offre.statut,
        disponibilite: offre.disponibilite,
        contact_gerance: offre.contact_gerance,
        contact_annonceur: offre.contact_annonceur,
        contact_visite: offre.contact_visite
      },
      client: client ? {
        client_id: client.id,
        prenom: profile?.prenom ?? null,
        nom: profile?.nom ?? null,
        email: profile?.email ?? null,
        telephone: profile?.telephone ?? null,
        date_naissance: client.date_naissance,
        nationalite: client.nationalite,
        type_permis: client.type_permis,
        situation_familiale: client.situation_familiale,
        profession: client.profession,
        employeur: client.employeur,
        type_contrat: client.type_contrat,
        revenus_mensuels: client.revenus_mensuels,
        charges_mensuelles: client.charges_mensuelles,
        adresse: client.adresse,
        nombre_occupants: client.nombre_occupants,
        animaux: client.animaux,
        statut: client.statut
      } : null,
      co_candidats: candidates ?? [],
      documents: (documents ?? []).map((d) => ({
        document_id: d.id,
        nom: d.nom,
        type_document: d.type_document,
        mime: d.type,
        taille: d.taille,
        statut: d.statut,
        date_upload: toZurichISO(d.date_upload),
        candidate_id: d.candidate_id
      }))
    });
  }
});

// src/lib/mcp/tools/create-document-download-link.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var BUCKET = "client-documents";
var EXPIRES_SECONDS = 60;
function storagePath(url) {
  let path = url.trim();
  const marker = `/storage/v1/object/`;
  const idx = path.indexOf(marker);
  if (idx >= 0) {
    path = path.slice(idx + marker.length).replace(/^(public|sign|authenticated)\//, "");
    path = path.split("?")[0];
  }
  if (path.startsWith(`${BUCKET}/`)) path = path.slice(BUCKET.length + 1);
  return path;
}
var create_document_download_link_default = defineTool3({
  name: "create_document_download_link",
  title: "Lien de t\xE9l\xE9chargement temporaire",
  description: "Cr\xE9e une URL sign\xE9e de 60 secondes pour UN SEUL document du dossier client. Aucun binaire ni lien permanent n'est renvoy\xE9.",
  inputSchema: {
    document_id: z3.string().uuid().describe("Identifiant du document \xE0 t\xE9l\xE9charger.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ document_id }, ctx) => {
    const { supabase, userId } = await requireAutomationOperator(ctx);
    const { data: doc, error } = await supabase.from("documents").select("id, nom, url, type, taille, client_id, user_id, type_document").eq("id", document_id).maybeSingle();
    if (error) throw new Error(error.message);
    if (!doc) {
      await auditLog(supabase, { actor_user_id: userId, tool: "create_document_download_link", document_id, outcome: "denied", detail: "document introuvable ou non autoris\xE9" });
      throw new ToolError3("404 not found: document introuvable ou non autoris\xE9.");
    }
    if (!doc.url || doc.url.startsWith("data:")) {
      throw new ToolError3("400 invalid: ce document n'est pas stock\xE9 dans le stockage de fichiers.");
    }
    const path = storagePath(doc.url);
    const { data: signed, error: signErr } = await supabase.storage.from(BUCKET).createSignedUrl(path, EXPIRES_SECONDS);
    if (signErr || !signed?.signedUrl) {
      await auditLog(supabase, { actor_user_id: userId, tool: "create_document_download_link", document_id, client_id: doc.client_id, outcome: "denied", detail: signErr?.message ?? "signature refus\xE9e" });
      throw new ToolError3(`403 forbidden: lien impossible (${signErr?.message ?? "acc\xE8s refus\xE9"}).`);
    }
    await auditLog(supabase, {
      actor_user_id: userId,
      tool: "create_document_download_link",
      document_id,
      client_id: doc.client_id,
      filename: doc.nom,
      size_bytes: doc.taille ?? null,
      outcome: "granted"
    });
    return textResult({
      document_id: doc.id,
      nom: doc.nom,
      type_document: doc.type_document,
      mime: doc.type,
      download_url: signed.signedUrl,
      expires_in_seconds: EXPIRES_SECONDS,
      expires_at: toZurichISO(new Date(Date.now() + EXPIRES_SECONDS * 1e3))
    });
  }
});

// src/lib/mcp/tools/upload-prepared-pdf.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var BUCKET2 = "client-documents";
var MAX_BYTES = 10 * 1024 * 1024;
function sanitizeFilename(input) {
  const base = input.split(/[\\/]/).pop() ?? "document.pdf";
  const cleaned = base.normalize("NFKD").replace(/[^\w.\- ]+/g, "_").replace(/\s+/g, "_").replace(/_{2,}/g, "_").slice(0, 120);
  return cleaned.toLowerCase().endsWith(".pdf") ? cleaned : `${cleaned}.pdf`;
}
function decodeBase64(b64) {
  const clean = b64.replace(/^data:application\/pdf;base64,/, "").replace(/\s+/g, "");
  const binary = atob(clean);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
var upload_prepared_pdf_default = defineTool4({
  name: "upload_prepared_pdf",
  title: "D\xE9poser un PDF pr\xE9par\xE9",
  description: "Ajoute (INSERT uniquement) un PDF pr\xE9par\xE9 au dossier du client d'une postulation. Valide la signature %PDF, la taille, le nom de fichier et d\xE9tecte les doublons.",
  inputSchema: {
    postulation_id: z4.string().uuid().describe("Identifiant de l'offre (postulation) concern\xE9e."),
    filename: z4.string().describe("Nom du fichier PDF, par ex. dossier_candidature.pdf."),
    content_base64: z4.string().describe("Contenu du PDF encod\xE9 en base64."),
    type_document: z4.string().describe("Cat\xE9gorie du document dans le CRM (d\xE9faut : dossier_candidature).").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const { supabase, userId } = await requireAutomationOperator(ctx);
    const filename = sanitizeFilename(input.filename);
    const { data: offre, error: offreErr } = await supabase.from("offres").select("id, client_id, adresse").eq("id", input.postulation_id).maybeSingle();
    if (offreErr) throw new Error(offreErr.message);
    if (!offre) {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", filename, outcome: "denied", detail: "postulation introuvable ou non autoris\xE9e" });
      throw new ToolError4("404 not found: postulation introuvable ou non autoris\xE9e.");
    }
    const { data: client } = await supabase.from("clients").select("id, user_id").eq("id", offre.client_id).maybeSingle();
    if (!client?.user_id) {
      throw new ToolError4("409 conflict: le client de cette postulation n'a pas de compte utilisateur associ\xE9.");
    }
    let bytes;
    try {
      bytes = decodeBase64(input.content_base64);
    } catch {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", client_id: client.id, filename, outcome: "invalid", detail: "base64 illisible" });
      throw new ToolError4("400 invalid: content_base64 n'est pas un base64 valide.");
    }
    if (bytes.byteLength === 0 || bytes.byteLength > MAX_BYTES) {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", client_id: client.id, filename, size_bytes: bytes.byteLength, outcome: "invalid", detail: "taille hors limites" });
      throw new ToolError4(`400 invalid: taille de fichier invalide (max ${MAX_BYTES} octets).`);
    }
    const header = String.fromCharCode(...bytes.slice(0, 5));
    if (header !== "%PDF-") {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", client_id: client.id, filename, size_bytes: bytes.byteLength, outcome: "invalid", detail: "signature %PDF absente" });
      throw new ToolError4("400 invalid: le fichier n'est pas un PDF (signature %PDF- absente).");
    }
    const { data: existing } = await supabase.from("documents").select("id, nom, taille").eq("client_id", client.id).eq("nom", filename).limit(5);
    const duplicate = (existing ?? []).find((d) => d.taille === bytes.byteLength);
    if (duplicate) {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", client_id: client.id, document_id: duplicate.id, filename, size_bytes: bytes.byteLength, outcome: "duplicate" });
      throw new ToolError4(`409 conflict: document d\xE9j\xE0 pr\xE9sent (document_id ${duplicate.id}).`);
    }
    const path = `${client.user_id}/postulations/${offre.id}/${Date.now()}-${filename}`;
    const { error: upErr } = await supabase.storage.from(BUCKET2).upload(path, bytes, {
      contentType: "application/pdf",
      upsert: false
    });
    if (upErr) {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", client_id: client.id, filename, size_bytes: bytes.byteLength, outcome: "denied", detail: upErr.message });
      throw new ToolError4(`403 forbidden: d\xE9p\xF4t refus\xE9 (${upErr.message}).`);
    }
    const { data: inserted, error: insErr } = await supabase.from("documents").insert({
      nom: filename,
      type: "application/pdf",
      taille: bytes.byteLength,
      url: path,
      user_id: client.user_id,
      client_id: client.id,
      offre_id: offre.id,
      type_document: input.type_document ?? "dossier_candidature",
      statut: "en attente"
    }).select("id, nom, date_upload").single();
    if (insErr) {
      await auditLog(supabase, { actor_user_id: userId, tool: "upload_prepared_pdf", client_id: client.id, filename, size_bytes: bytes.byteLength, outcome: "denied", detail: insErr.message });
      throw new ToolError4(`403 forbidden: enregistrement refus\xE9 (${insErr.message}).`);
    }
    await auditLog(supabase, {
      actor_user_id: userId,
      tool: "upload_prepared_pdf",
      client_id: client.id,
      document_id: inserted.id,
      filename,
      size_bytes: bytes.byteLength,
      outcome: "granted"
    });
    return textResult({
      document_id: inserted.id,
      nom: inserted.nom,
      client_id: client.id,
      postulation_id: offre.id,
      taille_octets: bytes.byteLength,
      date_upload: toZurichISO(inserted.date_upload)
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ydljsdscdnqrqnjvqela";
var mcp_default = defineMcp({
  name: "logisorama-logiciel-crm-immo-rama",
  title: "Logisorama - Logiciel CRM Immo-rama",
  version: "1.0.0",
  instructions: "Outils du CRM Logisorama pour le flux \xAB Postulations \xBB. Utilisez list_pending_postulations pour lister les postulations \xE0 faire, get_postulation_context pour obtenir le dossier born\xE9 d'une postulation, create_document_download_link pour obtenir un lien sign\xE9 de 60 s vers un document, et upload_prepared_pdf pour d\xE9poser le PDF de candidature pr\xE9par\xE9. Toutes les actions s'ex\xE9cutent avec l'identit\xE9 de l'utilisateur connect\xE9 (r\xF4le automation_operator requis).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_pending_postulations_default, get_postulation_context_default, create_document_download_link_default, upload_prepared_pdf_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
