-- Add all missing columns to clients table to match CSV structure
ALTER TABLE clients
ADD COLUMN IF NOT EXISTS date_naissance date,
ADD COLUMN IF NOT EXISTS adresse text,
ADD COLUMN IF NOT EXISTS etat_civil text,
ADD COLUMN IF NOT EXISTS gerance_actuelle text,
ADD COLUMN IF NOT EXISTS contact_gerance text,
ADD COLUMN IF NOT EXISTS loyer_actuel numeric,
ADD COLUMN IF NOT EXISTS depuis_le date,
ADD COLUMN IF NOT EXISTS pieces_actuel integer,
ADD COLUMN IF NOT EXISTS motif_changement text,
ADD COLUMN IF NOT EXISTS employeur text,
ADD COLUMN IF NOT EXISTS date_engagement date,
ADD COLUMN IF NOT EXISTS charges_extraordinaires boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS montant_charges_extra numeric,
ADD COLUMN IF NOT EXISTS poursuites boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS curatelle boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS souhaits_particuliers text,
ADD COLUMN IF NOT EXISTS nombre_occupants integer,
ADD COLUMN IF NOT EXISTS utilisation_logement text,
ADD COLUMN IF NOT EXISTS animaux boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS instrument_musique boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS vehicules boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS numero_plaques text,
ADD COLUMN IF NOT EXISTS decouverte_agence text;