-- Enable only after the migration and template have been verified.
insert into newsletter_sequence_welcomes(campaign_id,name,subject,preheader,html) values ('120248622162110217','Druey 18','Votre visite — Appartement 2.5 pièces, avenue Druey 18','Photos, conditions de location et réservation de visite à Lausanne.','<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="logisorama-email-layout" content="corporate-v1"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Votre visite à l’avenue Druey 18</title><style>@media screen and (max-width:520px){.email-stack{display:block!important;width:100%!important;padding-left:0!important;padding-right:0!important;box-sizing:border-box!important}.email-outer{padding:0!important}.email-pad{padding-left:24px!important;padding-right:24px!important}.email-heading{font-size:26px!important;line-height:32px!important}.email-brandline{font-size:9px!important;letter-spacing:.7px!important}}</style></head>
<body style="margin:0;padding:0;background:#eef0eb;font-family:Arial,Helvetica,sans-serif;">
<div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">Photos, conditions de location et réservation de visite à Lausanne.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#eef0eb"><tr><td align="center" class="email-outer" style="padding:24px 12px;">
<!--[if mso]><table role="presentation" width="640"><tr><td><![endif]-->
<table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="width:100%;max-width:640px;border-top:4px solid #205a43;">
<tr><td class="email-pad" style="padding:24px 36px;border-bottom:1px solid #e7ebe5;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td><div style="font-size:27px;line-height:30px;font-weight:bold;letter-spacing:-1px;color:#193d2c;">Logisorama</div><img src="https://logisorama.ch/__l5e/assets-v1/620cc5b1-18df-42ab-86d6-2ea17731daef/logisorama-email-logo.png" width="144" height="40" alt="Logisorama" style="display:block;border:0;margin-top:3px;"></td><td align="right" class="email-brandline" style="font-size:10px;line-height:17px;letter-spacing:1.2px;color:#677a6c;">APPARTEMENT À LOUER · LAUSANNE</td></tr></table></td></tr>
<tr><td class="email-pad" style="padding:32px 36px 30px;font-size:16px;line-height:26px;color:#5c665e;overflow-wrap:anywhere;">
<h1 class="email-heading" style="margin:0 0 22px;font:700 30px/36px Arial,Helvetica,sans-serif;letter-spacing:-.7px;color:#1c523c;">Votre visite à l’avenue Druey 18</h1><p>Bonjour,</p><p>Merci pour votre intérêt pour l’appartement de <strong>2.5 pièces à Lausanne, avenue Druey 18</strong>.</p><p>Vous trouverez les photos, les conditions de location et les informations du logement dans l’annonce ci-dessous. Pour organiser une visite, sélectionnez directement un créneau disponible sur la page :</p><table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:24px 0;"><tr><td bgcolor="#205a43" style="border-radius:5px;mso-padding-alt:14px 22px;"><a href="https://logisorama.ch/annonces/lumineux-2-5-pi-ces-lausanne-disponible-d-s-le-15-octobre-lausanne-ap-456dfeb2" style="display:inline-block;padding:14px 22px;border:1px solid #205a43;border-radius:5px;color:#ffffff;background:#205a43;font:700 16px/22px Arial,Helvetica,sans-serif;text-decoration:none;text-align:center;">Voir l’annonce et réserver une visite</a></td></tr></table><p>Au plaisir de vous rencontrer !</p></td></tr>
<tr><td class="email-pad" style="padding:22px 36px;background:#f3f4ed;border-top:1px solid #e7ebe5;font-size:13px;line-height:22px;color:#435b47;"><strong>L’équipe Logisorama</strong><br>Votre recherche de logement, au même endroit.</td></tr>
<tr><td class="email-pad" style="padding:22px 36px;font-size:12px;line-height:20px;color:#7b847a;"><strong>Logisorama · Immo-rama</strong><br><a href="https://logisorama.ch" style="color:#205a43;">logisorama.ch</a> · <a href="mailto:support@logisorama.ch" style="color:#205a43;">support@logisorama.ch</a></td></tr>
</table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>');
