UPDATE public.mandate_contract_texts SET is_active = false WHERE is_active = true;
INSERT INTO public.mandate_contract_texts (version, title, content, is_active)
VALUES ('2026-08-19', 'Contrat de mandat de recherche immobilière', $ct$Article 1 — Parties
Le présent contrat est conclu entre : Immo-rama.ch, entreprise individuelle exploitée par M. Christ Ramazani, Chemin de l'Esparcette 5, 1023 Crissier (VD), Suisse, IDE CHE-442.303.796, joignable au 021 625 95 05 et à info@immo-rama.ch, ci-après « l'Agence », et la personne identifiée lors de la conclusion électronique du présent contrat, ci-après « le Client ». Les données d'identité, coordonnées et critères de recherche communiqués électroniquement par le Client font partie intégrante du présent contrat.

Article 2 — Objet et nature du mandat
Le Client charge l'Agence de l'accompagner dans la recherche d'un logement à louer ou, lorsqu'une mission d'acquisition a expressément été sélectionnée, d'un bien immobilier à acheter. Selon la mission choisie, l'intervention de l'Agence peut notamment comprendre : la recherche et la sélection de biens, le matching automatisé ou assisté par intelligence artificielle, la transmission d'offres, l'aide à la constitution du dossier, l'organisation ou la réalisation de visites, les visites à distance, la communication avec les régies, propriétaires ou vendeurs, l'assistance administrative et le dépôt de candidatures. Le contrat comporte des prestations relevant du mandat ainsi que, lorsque la rémunération dépend de la conclusion du contrat recherché, des éléments de courtage au sens des art. 412 ss CO. L'Agence est tenue à une obligation de diligence et de moyens, et non à une obligation de résultat. Elle ne garantit ni l'attribution d'un logement, ni l'acceptation d'une candidature, ni l'obtention d'un financement, ni la conclusion d'une vente.

Article 3 — Exclusivité
Pendant la durée du mandat, le Client confie à l'Agence à titre exclusif la mission définie au présent contrat. Le Client reste libre de consulter les annonces immobilières et de recevoir des propositions par ses propres moyens. Il s'engage cependant à informer rapidement l'Agence de toute opportunité correspondant au mandat et à signaler toute démarche effectuée directement concernant un bien déjà identifié ou présenté par l'Agence. L'exclusivité ne prive en aucun cas le Client de son droit impératif de résilier le mandat conformément à l'art. 404 CO.

Article 4 — Durée
Le mandat est initialement conclu pour trois mois à compter de son acceptation électronique. À l'issue de cette période, il est renouvelé pour une nouvelle période de trois mois sauf opposition de l'une des parties. Cette durée contractuelle n'empêche pas chacune des parties de mettre fin au mandat en tout temps conformément à l'art. 404 CO.

Article 5 — Rémunération en cas de location
Lorsque, grâce à l'indication, à la recherche, à la négociation, à la postulation ou à une autre intervention causalement pertinente de l'Agence, le Client conclut un contrat de bail portant sur un logement faisant partie de la mission confiée, une commission correspondant à un mois de loyer brut, charges comprises, est due à l'Agence. La TVA au taux légal applicable, actuellement 8,1 %, s'ajoute à la commission si l'Agence est assujettie à la TVA au moment où la prestation devient imposable. La commission devient exigible dès la conclusion du bail ayant résulté de l'intervention de l'Agence. Le droit au salaire du courtier est soumis aux conditions des art. 412 ss CO, notamment à l'existence d'un lien suffisant entre l'intervention du courtier et la conclusion du contrat recherché. Une même attribution de logement ne peut donner lieu qu'à une seule commission Immo-rama.ch. Lorsqu'un dépôt de candidature effectué depuis Logisorama.ch concerne déjà un bien couvert par le présent mandat, la commission de postulation et la commission prévue au présent article ne se cumulent pas.

Article 6 — Recherche en vue d'un achat
Lorsque la mission concerne l'acquisition d'un bien immobilier, les prestations de recherche peuvent être exécutées dans le cadre du présent mandat. Toute rémunération ou commission spécifique liée à l'acquisition doit toutefois être définie dans une offre, annexe ou convention tarifaire communiquée et acceptée par le Client avant qu'elle puisse être exigée. À défaut d'une telle convention tarifaire acceptée, aucune commission d'acquisition ne peut être réclamée sur la seule base de l'article 5, celui-ci étant exclusivement applicable à la location.

Article 7 — Acompte d'activation
À la conclusion du mandat, le Client verse un acompte de CHF 300.–. Cet acompte constitue une avance imputée sur les sommes éventuellement dues à l'Agence conformément au présent contrat. En cas de conclusion d'un bail donnant droit à la commission prévue à l'article 5, les CHF 300.– sont intégralement déduits du montant facturé. L'acompte ne constitue pas une peine conventionnelle destinée à empêcher le Client de résilier le mandat. En cas de résiliation, les droits respectifs des parties sont déterminés conformément au présent contrat et aux dispositions impératives du droit suisse, notamment l'art. 404 CO. Si une résiliation intervient en temps inopportun et cause un dommage juridiquement indemnisable à l'autre partie, les droits découlant de l'art. 404 al. 2 CO demeurent réservés.

Article 8 — Obligations du Client
Le Client s'engage notamment à : fournir des renseignements exacts, complets et actualisés ; fournir les documents raisonnablement nécessaires à la constitution de son dossier ; signaler rapidement tout changement professionnel, financier ou personnel pertinent pour la recherche ; ne pas fournir de documents falsifiés ou trompeurs ; communiquer à l'Agence les démarches déjà entreprises concernant un bien présenté par celle-ci ; respecter les rendez-vous et visites convenus ou prévenir suffisamment tôt en cas d'empêchement ; informer l'Agence lorsqu'un bail ou un contrat est conclu concernant un bien entrant dans le champ du mandat ; informer les garants, co-candidats et autres personnes dont il transmet les données.

Article 9 — Obligations de l'Agence
L'Agence s'engage notamment à : exécuter le mandat avec diligence ; rechercher et sélectionner des opportunités compatibles avec les critères communiqués ; présenter de manière loyale les informations dont elle dispose ; préserver la confidentialité du dossier du Client ; limiter la transmission des documents et données à ce qui est nécessaire à la recherche et aux candidatures ; signaler au Client les conflits d'intérêts importants dont elle a connaissance ; ne pas garantir une attribution ou une transaction qu'elle ne maîtrise pas.

Article 10 — Absence de double rémunération et conflits d'intérêts
Lorsque l'Agence intervient également pour une régie, un propriétaire, un vendeur ou un autre intervenant concernant le même bien, elle veille à identifier et gérer tout conflit d'intérêts. L'Agence ne doit pas percevoir de rémunérations incompatibles avec ses obligations envers son mandant ou contraires aux règles de la bonne foi. L'art. 415 CO prévoit notamment la perte du droit au salaire du courtier lorsqu'il agit dans l'intérêt du tiers contractant au mépris de ses obligations ou perçoit de celui-ci une rémunération dans des circonstances contraires à la bonne foi.

Article 11 — Protection des données
Dans le cadre du mandat, l'Agence traite les données nécessaires à la fourniture de ses services, notamment les données d'identité et de contact, critères de recherche, situation professionnelle et financière, données relatives au ménage, échanges, candidatures, coordonnées bancaires et documents justificatifs. Ces documents peuvent notamment inclure des fiches de salaire, extraits du registre des poursuites, pièces d'identité, permis de séjour, contrats de travail ainsi que des documents concernant des co-candidats ou garants. Ces documents ne constituent pas automatiquement des « données personnelles sensibles » au sens de la LPD, mais certains peuvent contenir ou révéler de telles données. L'Agence applique un niveau de protection adapté à leur caractère confidentiel. Les données sont traitées notamment afin d'exécuter le mandat, gérer le compte et les candidatures, communiquer avec le Client, transmettre les dossiers nécessaires aux régies, propriétaires, vendeurs ou partenaires concernés, organiser les visites, assurer la facturation, gérer les preuves contractuelles, prévenir les abus et sécuriser la plateforme. Les informations détaillées relatives au traitement, aux prestataires, aux transferts internationaux, aux durées de conservation et aux droits des personnes concernées figurent dans la Politique de confidentialité de Logisorama.ch. Le contact unique en matière de protection des données est : info@immo-rama.ch.

Article 12 — Non-contournement
Lorsque l'Agence a identifié, présenté, organisé la visite d'un bien ou joué un rôle causal significatif dans sa découverte ou sa négociation, le Client s'engage à ne pas contourner intentionnellement l'Agence afin d'éviter la rémunération convenue. Lorsque le Client conclut directement ou indirectement, pendant le mandat ou dans les douze mois suivant sa fin, un contrat portant sur un bien effectivement présenté par l'Agence durant le mandat, la commission demeure due uniquement lorsque les conditions légales du droit au courtage, notamment le lien de causalité entre l'activité de l'Agence et la conclusion du contrat, sont réunies. La présente clause ne crée pas une commission pour un bien sans rapport causal suffisant avec l'activité de l'Agence.

Article 13 — Résiliation
Chaque partie peut révoquer ou répudier le mandat en tout temps, conformément à l'art. 404 al. 1 CO. La résiliation peut être communiquée par écrit ou au moyen de la fonctionnalité prévue dans l'espace client lorsqu'elle est disponible. Les éventuels effets financiers d'une résiliation en temps inopportun sont régis par l'art. 404 al. 2 CO. Aucune disposition du présent contrat ne doit être interprétée comme supprimant ou limitant le droit impératif de résiliation prévu par l'art. 404 CO.

Article 14 — Responsabilité
L'Agence répond des dommages qu'elle cause conformément au droit suisse applicable. Elle ne répond pas des décisions prises par les régies, propriétaires, vendeurs, établissements financiers, autorités ou autres tiers indépendants. Elle ne garantit ni l'exactitude d'informations provenant directement de tiers, ni la disponibilité continue d'un bien, ni l'acceptation du Client. Toute exclusion ou limitation de responsabilité prévue contractuellement demeure soumise aux limites impératives du droit suisse.

Article 15 — Droit applicable et for
Le contrat est régi par le droit suisse. Sous réserve des fors impératifs ou semi-impératifs prévus par la loi, les tribunaux compétents sont ceux du canton de Vaud. Lorsque le Client agit en qualité de consommateur, les fors protecteurs prévus notamment par le Code de procédure civile demeurent intégralement réservés.

Article 16 — Conclusion électronique et acceptation
Le contrat peut être conclu électroniquement. L'identité déclarée du Client, la version du contrat acceptée, la date et l'heure, les consentements ou confirmations effectués, ainsi que la signature électronique ou manuscrite capturée peuvent être journalisés afin de documenter la conclusion du contrat. Le Client dispose, avant validation finale, de la possibilité de consulter le contrat, vérifier les informations saisies et corriger les erreurs. Une confirmation électronique de la conclusion du mandat lui est ensuite transmise ou mise à disposition.$ct$, true);

ALTER TABLE public.mandates
  ADD COLUMN IF NOT EXISTS legal_objet boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS legal_obligation_moyens boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS legal_transmission_dossier boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS legal_garants_cocandidats boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS legal_cgu boolean NOT NULL DEFAULT false;